export const EGYPT_GOVERNORATES = [
    'Cairo',
    'Giza',
    'Alexandria',
    'Dakahlia',
    'Red Sea',
    'Beheira',
    'Fayoum',
    'Gharbia',
    'Ismailia',
    'Menofia',
    'Minya',
    'Qaliubiya',
    'New Valley',
    'North Sinai',
    'Port Said',
    'Qena',
    'South Sinai',
    'Sohag',
    'Suez',
    'Aswan',
    'Assiut',
    'Beni Suef',
    'Damietta',
    'Sharqia',
    'Kafr El Sheikh',
    'Matruh',
    'Luxor',
    'Qalyubia',
    'New Cairo',
    '6th of October',
];

